version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "443:443"
